#!/bin/bash
if [ $# -lt 2 ]
then
  cat << ENDDOC
syntax: <output name> <path to head.tex template> <version>
List of song-files is read from stdin.
Files are outputted into the working directory.
ENDDOC
  exit 1
fi

#cd $(echo "$0" | sed 's=/[^/]*$==g')
workdir=$(realpath "$0" | sed 's=/[^/]*$==g')
origdir=`pwd`
outdir=`pwd`

name="$1"
head="$2"
version="$3"
colwidth=45
songs=`mktemp`


echo '###########################'
echo "PROCESSING SONGBOOK: $name with $head $version"
echo '###########################'

cat | grep -v '[/]\..*.swp' | xargs realpath > $songs
echo "$version" > $workdir/ver.tex
cat "$head" > $workdir/head.tex
cd "$workdir"

for colmode in 3cols adaptive
do
  echo "PROCESSING MODE $colmode" > /dev/tty
  echo "WRITTING CONTENT INTO $workdir/content-$colmode.tex" > /dev/tty
  cat $songs | while read file # file in $input/*
  do
    if [ -f $file ]
    then
      width=$(cat $file | sed 's/\[[^]]*\]//g' | wc -L)
      [ $width -lt $colwidth -o $width -gt $(( $colwidth + 5 )) ] || echo "$file is just a bit over colwidth!" > /dev/tty
      cols=$(( ( $colwidth /  $width ) + 1 ))
      [ $colmode == 3cols ] && cols=3
      echo "\\songcolumns{$cols}"
      cat $file | tr '\n\t' '\t\n' | sed 's/\t\t\t*/\t\t/g' | tr '\n\t' '\t\n' | grep -v '^#' | sed 's/[#[]/\\&/g' | awk '
      BEGIN {first=1;}
      /===/ {printf("\\beginverse\n"); next}
      /^ *$/ {printf("\\endverse\n\\beginverse\n"); next}
      // { if(first ==1){first = 0; printf("\\beginsong{%s}\n", $0)} else printf("%s\n", $0) }
      END { printf("\n\\endverse\n\\endsong\n\n\n"); }
      ' | sed 's/&apos;/'"'"'/g;s/&quot;/"/g;s/[`´]/'"'"'/g;s/„/"/g;'
    else
      echo FILE NOT FOUND: $file at pwd $(pwd) > /dev/tty
    fi
    echo "PROCESSING $file" > /dev/tty
  done > "$workdir/content-$colmode.tex"
done

latex template-a5.tex  && \
pdflatex template-a5.tex  && \
pdflatex template-a5-booklet.tex && \
pdflatex template-a4.tex 


for i in template*pdf template*dvi
do
  mv $i "$outdir/$(echo "$i" | sed 's/template/'"$name"'/g;')"
done


rm $songs cbtitle.* *.log content*tex
ls | grep 'template.*' | grep -v '.tex$' | xargs rm

